# Generated by Django 4.2.7 on 2025-08-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Salida'),
        ),
    ]
