# Generated by Django 4.2.21 on 2025-08-26 07:20

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0002_alter_reserva_fecha_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='subtotal_ajustes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal Ajustes'),
        ),
        migrations.CreateModel(
            name='AjustePrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('extra', 'Cargo Extra'), ('descuento', 'Descuento')], max_length=20, verbose_name='Tipo de Ajuste')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Porcentaje')),
                ('es_porcentaje', models.BooleanField(default=False, verbose_name='¿Es porcentaje?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_precio', to='hotel.reserva', verbose_name='Reserva')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Creó')),
            ],
            options={
                'verbose_name': 'Ajuste de Precio',
                'verbose_name_plural': 'Ajustes de Precio',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
