# Generated by Django 5.1.4 on 2025-09-08 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_rename_reserva_to_hospedada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajusteprecio',
            name='hospedada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_precio', to='hotel.hospedada', verbose_name='Hospedada'),
        ),
        migrations.AlterField(
            model_name='consumohabitacion',
            name='hospedada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hospedada', verbose_name='Hospedada'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='hospedada',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotel.hospedada', verbose_name='Hospedada'),
        ),
        migrations.AlterField(
            model_name='hospedada',
            name='numero_hospedada',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Hospedada'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='hospedada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hospedada', verbose_name='Hospedada'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reserva', models.CharField(max_length=20, unique=True, verbose_name='Número de Reserva')),
                ('fecha_entrada_prevista', models.DateField(verbose_name='Fecha de Entrada Prevista')),
                ('fecha_salida_prevista', models.DateField(verbose_name='Fecha de Salida Prevista')),
                ('numero_huespedes', models.PositiveIntegerField(default=1, verbose_name='Número de Huéspedes')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('convertida', 'Convertida a Hospedada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('precio_acordado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Acordado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.cliente', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.empresa', verbose_name='Empresa')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.habitacion', verbose_name='Habitación')),
                ('hospedada_convertida', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserva_origen', to='hotel.hospedada', verbose_name='Hospedada Resultante')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Creó')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
