# Generated by Django 5.1.4 on 2025-09-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0005_alter_ajusteprecio_hospedada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospedada",
            name="deudor",
            field=models.CharField(
                blank=True,
                choices=[("cliente", "Cliente"), ("empresa", "Empresa")],
                max_length=20,
                verbose_name="Deudor",
            ),
        ),
        migrations.AddField(
            model_name="hospedada",
            name="fecha_checkout",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Checkout"
            ),
        ),
        migrations.AddField(
            model_name="hospedada",
            name="monto_deuda",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Monto de Deuda",
            ),
        ),
        migrations.AddField(
            model_name="hospedada",
            name="observaciones_deuda",
            field=models.TextField(blank=True, verbose_name="Observaciones de Deuda"),
        ),
        migrations.AddField(
            model_name="hospedada",
            name="tiene_deuda",
            field=models.BooleanField(default=False, verbose_name="Tiene Deuda"),
        ),
    ]
