# Generated by Django 5.1.4 on 2025-09-08 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0006_hospedada_deudor_hospedada_fecha_checkout_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ElementoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Elemento"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("basico", "Básico"),
                            ("sexshop", "Sex Shop"),
                            ("premium", "Premium"),
                            ("limpieza", "Limpieza"),
                            ("tecnologia", "Tecnología"),
                        ],
                        default="basico",
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "costo_reposicion",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Costo de Reposición",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Elemento de Inventario",
                "verbose_name_plural": "Elementos de Inventario",
                "ordering": ["categoria", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del Servicio"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "precio_sugerido",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio Sugerido",
                    ),
                ),
                (
                    "requiere_precio",
                    models.BooleanField(
                        default=True, verbose_name="Requiere Precio Manual"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "icono",
                    models.CharField(
                        default="fas fa-concierge-bell",
                        max_length=50,
                        verbose_name="Icono (Font Awesome)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Servicio",
                "verbose_name_plural": "Tipos de Servicios",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="FaltanteCheckout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Cantidad Faltante"
                    ),
                ),
                (
                    "costo_cobrado",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Costo Cobrado"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "elemento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel.elementoinventario",
                        verbose_name="Elemento",
                    ),
                ),
                (
                    "hospedada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faltantes",
                        to="hotel.hospedada",
                        verbose_name="Hospedada",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado Por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faltante en Checkout",
                "verbose_name_plural": "Faltantes en Checkout",
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.CreateModel(
            name="ServicioHospedada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio"
                    ),
                ),
                (
                    "cantidad",
                    models.PositiveIntegerField(default=1, verbose_name="Cantidad"),
                ),
                (
                    "fecha_servicio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha del Servicio"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "hospedada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicios",
                        to="hotel.hospedada",
                        verbose_name="Hospedada",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado Por",
                    ),
                ),
                (
                    "tipo_servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel.tiposervicio",
                        verbose_name="Tipo de Servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio de Hospedada",
                "verbose_name_plural": "Servicios de Hospedadas",
                "ordering": ["-fecha_servicio"],
            },
        ),
        migrations.CreateModel(
            name="InventarioHabitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.PositiveIntegerField(default=1, verbose_name="Cantidad"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("bueno", "Bueno"),
                            ("regular", "Regular"),
                            ("malo", "Malo"),
                            ("faltante", "Faltante"),
                        ],
                        default="bueno",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "ultima_revision",
                    models.DateTimeField(auto_now=True, verbose_name="Última Revisión"),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "elemento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel.elementoinventario",
                        verbose_name="Elemento",
                    ),
                ),
                (
                    "habitacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventario",
                        to="hotel.habitacion",
                        verbose_name="Habitación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventario de Habitación",
                "verbose_name_plural": "Inventarios de Habitaciones",
                "ordering": ["habitacion", "elemento__categoria", "elemento__nombre"],
                "unique_together": {("habitacion", "elemento")},
            },
        ),
    ]
